"""Phase-appropriate language as prose on the feedback row

Revision ID: c1f4a83b7d29
Revises: d3b8f1a05c67

F-42's block, written by the same model call as `feedback.summary`.

Added nullable and left unfilled on purpose. There is no value to backfill an
existing row with: the wrap-ups already stored were generated by a prompt that
never looked at the phases, and writing an empty string would make them look
analysed. NULL means "not analysed", which is what the frontend omits the block
for.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "c1f4a83b7d29"
down_revision: Union[str, None] = "d3b8f1a05c67"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("feedback", sa.Column("phase_language", sa.Text(), nullable=True))


def downgrade() -> None:
    op.drop_column("feedback", "phase_language")
