"""Index session.subject_id for the per-user history

Revision ID: 18f5098dfb1b
Revises: e4a9c07b2f31

The one indexed column in the schema that is not a foreign key, and the first
index added for a read path rather than for a delete.

ADR 0028 declined secondary indexes while nothing queried the schema, and ADR
0052 -- which indexed every foreign key -- singled this column out as the
exception: it "stays unindexed until authentication (ADR 0009) makes per-user
history possible at all". That condition is met. `subject_id` now holds the
real Keycloak `sub`, and `GET /api/sessions` filters on it and on nothing else,
so without this every listing sequentially scans the whole session table.

Autogenerated and left as generated: an index is one of the few changes
autogenerate gets right unaided, and `op.f()` marks the name as already
following the convention (ADR 0053) so it is not prefixed a second time.
"""
from typing import Sequence, Union

from alembic import op

revision: str = "18f5098dfb1b"
# Re-pointed when this branch merged into dev: both branches had autogenerated
# from a7c39e5f21b8, which would have left the chain with two heads and made
# `alembic upgrade head` refuse to run. The consent/retention revisions follow
# this one, so re-pointing it alone puts the whole branch behind dev's.
down_revision: Union[str, None] = "e4a9c07b2f31"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

IX_SESSION_SUBJECT = op.f("ix_session_subject_id")


def upgrade() -> None:
    op.create_index(IX_SESSION_SUBJECT, "session", ["subject_id"], unique=False)


def downgrade() -> None:
    op.drop_index(IX_SESSION_SUBJECT, table_name="session")
