"""Create initial persistence schema

Revision ID: 30351586b0a1
Revises: 
Create Date: 2026-08-11 19:44:43.659331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30351586b0a1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrik_typ',
    sa.Column('metrik_typ_id', sa.Integer(), nullable=False),
    sa.Column('schluessel', sa.String(length=60), nullable=False),
    sa.Column('bezeichnung', sa.String(length=120), nullable=False),
    sa.Column('einheit', sa.String(length=40), nullable=True),
    sa.Column('feature_id', sa.String(length=10), nullable=True),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('metrik_typ_id'),
    sa.UniqueConstraint('schluessel')
    )
    op.create_table('persona',
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('rolle', sa.String(length=120), nullable=False),
    sa.Column('haltung', sa.String(length=120), nullable=False),
    sa.Column('schwierigkeitsgrad', sa.String(length=40), nullable=False),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('persona_id')
    )
    op.create_table('sprache',
    sa.Column('sprache_code', sa.String(length=8), nullable=False),
    sa.Column('bezeichnung', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('sprache_code')
    )
    op.create_table('szenario',
    sa.Column('szenario_id', sa.Integer(), nullable=False),
    sa.Column('typ', sa.String(length=60), nullable=False),
    sa.Column('titel', sa.String(length=160), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('szenario_id')
    )
    op.create_table('session',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.String(length=64), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('szenario_id', sa.Integer(), nullable=False),
    sa.Column('sprache_code', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('gestartet_am', sa.DateTime(), nullable=False),
    sa.Column('beendet_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.persona_id'], ),
    sa.ForeignKeyConstraint(['sprache_code'], ['sprache.sprache_code'], ),
    sa.ForeignKeyConstraint(['szenario_id'], ['szenario.szenario_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('analysis_job',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('art', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('versuche', sa.Integer(), nullable=False),
    sa.Column('fehlertext', sa.Text(), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('feedback',
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('zusammenfassung', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ),
    sa.PrimaryKeyConstraint('feedback_id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('turn',
    sa.Column('turn_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('sprecher', sa.String(length=10), nullable=False),
    sa.Column('seq_index', sa.Integer(), nullable=False),
    sa.Column('start_offset_ms', sa.Integer(), nullable=False),
    sa.Column('dauer_ms', sa.Integer(), nullable=False),
    sa.Column('transkript', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ),
    sa.PrimaryKeyConstraint('turn_id')
    )
    op.create_table('befund',
    sa.Column('befund_id', sa.Integer(), nullable=False),
    sa.Column('turn_id', sa.Integer(), nullable=False),
    sa.Column('metrik_typ_id', sa.Integer(), nullable=True),
    sa.Column('kategorie', sa.String(length=60), nullable=False),
    sa.Column('offset_ms', sa.Integer(), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['metrik_typ_id'], ['metrik_typ.metrik_typ_id'], ),
    sa.ForeignKeyConstraint(['turn_id'], ['turn.turn_id'], ),
    sa.PrimaryKeyConstraint('befund_id')
    )
    op.create_table('messung',
    sa.Column('messung_id', sa.Integer(), nullable=False),
    sa.Column('turn_id', sa.Integer(), nullable=False),
    sa.Column('metrik_typ_id', sa.Integer(), nullable=False),
    sa.Column('wert', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('detail_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['metrik_typ_id'], ['metrik_typ.metrik_typ_id'], ),
    sa.ForeignKeyConstraint(['turn_id'], ['turn.turn_id'], ),
    sa.PrimaryKeyConstraint('messung_id')
    )
    op.create_table('feedbackpunkt',
    sa.Column('feedbackpunkt_id', sa.Integer(), nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('turn_id', sa.Integer(), nullable=True),
    sa.Column('befund_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['befund_id'], ['befund.befund_id'], ),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.feedback_id'], ),
    sa.ForeignKeyConstraint(['turn_id'], ['turn.turn_id'], ),
    sa.PrimaryKeyConstraint('feedbackpunkt_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedbackpunkt')
    op.drop_table('messung')
    op.drop_table('befund')
    op.drop_table('turn')
    op.drop_table('feedback')
    op.drop_table('analysis_job')
    op.drop_table('session')
    op.drop_table('szenario')
    op.drop_table('sprache')
    op.drop_table('persona')
    op.drop_table('metrik_typ')
    # ### end Alembic commands ###
