"""Add language and voice columns to persona

Revision ID: 407a1f8f2352
Revises: 9008fded73e9

Hand-written rather than autogenerated: the columns are added nullable and
backfilled before being made NOT NULL, so this also runs against a persona
table that already has rows, and the foreign key is named so downgrade() can
drop it. See ADR 0041.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '407a1f8f2352'
down_revision: Union[str, None] = '9008fded73e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

FK_NAME = "fk_persona_sprache_code"


def upgrade() -> None:
    op.add_column('persona', sa.Column('sprache_code', sa.String(length=8), nullable=True))
    op.add_column('persona', sa.Column('tts_stimme', sa.String(length=40), nullable=True))
    op.add_column('persona', sa.Column('kugelaudio_stimme_id', sa.Integer(), nullable=True))

    # Backfill for rows that predate these columns. Only one Persona exists so
    # far, and these are its values as previously hardcoded in personas.py —
    # not invented defaults. The Sprache row has to exist first, otherwise the
    # foreign key below has nothing to point at.
    op.execute(
        "INSERT INTO sprache (sprache_code, bezeichnung) VALUES ('de', 'Deutsch') "
        "ON CONFLICT (sprache_code) DO NOTHING"
    )
    op.execute(
        "UPDATE persona SET sprache_code = 'de', tts_stimme = 'de_male', "
        "kugelaudio_stimme_id = 1885 WHERE sprache_code IS NULL"
    )

    op.alter_column('persona', 'sprache_code', nullable=False)
    op.alter_column('persona', 'tts_stimme', nullable=False)
    op.alter_column('persona', 'kugelaudio_stimme_id', nullable=False)
    op.create_foreign_key(FK_NAME, 'persona', 'sprache', ['sprache_code'], ['sprache_code'])


def downgrade() -> None:
    op.drop_constraint(FK_NAME, 'persona', type_='foreignkey')
    op.drop_column('persona', 'kugelaudio_stimme_id')
    op.drop_column('persona', 'tts_stimme')
    op.drop_column('persona', 'sprache_code')
