"""English schema, named constraints, indexed foreign keys, enforced deletes

Revision ID: 5a7e1c9f4b02
Revises: b4e1a72c9d05
Create Date: 2026-09-02

Hand-written, not autogenerated. Autogenerate cannot recognise a rename -- it
would emit a drop of every German table and a create of every English one,
destroying whatever Sessions are already stored. Renaming in place keeps the
rows and lets Postgres carry the foreign keys along by itself.

One assumption is worth naming, because nothing here enforces it: the old
constraint names below are the ones a replayed chain produces. The initial
revision creates its foreign keys unnamed, and the convention in
backend/db/base.py -- which Alembic applies when replaying it -- arrived with
this revision. A database created before that carries Postgres' own
`<table>_<column>_fkey` names, and the drops below would not find them. The
tests always replay from empty, so they only ever see the case that works.

Five changes in one revision, because they only make sense together (each one
alone would leave the schema half-converted):

  1. German table, column and vocabulary names become English (ADR 0026).
  2. Persona gains the language and voice it is bound to (ADR 0041/0043), and
     Scenario the `active` flag that lets a retired one stay referenced.
  3. Constraints are renamed onto the convention in backend/db/base.py, so a
     future downgrade() can name what it drops.
  4. Every foreign-key column gets an index (ADR 0052).
  5. Ownership edges get ON DELETE CASCADE, optional back-references
     ON DELETE SET NULL, so deleting a Session works from raw SQL too.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5a7e1c9f4b02'
down_revision: Union[str, None] = 'b4e1a72c9d05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# --- 1. Names -------------------------------------------------------------

# (old, new) -- applied in this order on upgrade, reversed on downgrade.
TABLES = [
    ("persona_einwand", "persona_objection"),
    ("szenario", "scenario"),
    ("sprache", "language"),
    ("metrik_typ", "metric_type"),
    ("messung", "measurement"),
    ("befund", "finding"),
    ("feedbackpunkt", "feedback_point"),
]

# Keyed by the *new* table name: {table: [(old_column, new_column), ...]}
COLUMNS = {
    "persona": [
        ("schluessel", "key"),
        ("rolle", "role"),
        ("haltung", "traits"),
        ("verhalten", "behavior"),
        ("trainingsziel", "training_goal"),
        ("schwierigkeitsgrad", "difficulty"),
        ("aktiv", "active"),
    ],
    "persona_objection": [
        ("einwand_id", "objection_id"),
        ("reihenfolge", "position"),
    ],
    "scenario": [
        ("szenario_id", "scenario_id"),
        ("schluessel", "key"),
        ("typ", "scenario_type"),
        ("titel", "title"),
        ("beschreibung", "description"),
    ],
    "language": [
        ("sprache_code", "code"),
        ("bezeichnung", "name"),
    ],
    "metric_type": [
        ("metrik_typ_id", "metric_type_id"),
        ("schluessel", "key"),
        ("bezeichnung", "name"),
        ("einheit", "unit"),
        ("aktiv", "active"),
    ],
    "session": [
        ("oeffentliche_id", "extern_id"),
        ("szenario_id", "scenario_id"),
        ("sprache_code", "language_code"),
        ("gestartet_am", "started_at"),
        ("beendet_am", "ended_at"),
    ],
    "turn": [
        ("sprecher", "speaker"),
        ("dauer_ms", "duration_ms"),
        ("transkript", "transcript"),
    ],
    "measurement": [
        ("messung_id", "measurement_id"),
        ("metrik_typ_id", "metric_type_id"),
        ("wert", "value"),
    ],
    "finding": [
        ("befund_id", "finding_id"),
        ("metrik_typ_id", "metric_type_id"),
        ("kategorie", "category"),
        ("beschreibung", "description"),
    ],
    "feedback": [
        ("zusammenfassung", "summary"),
        ("erstellt_am", "created_at"),
    ],
    "feedback_point": [
        ("feedbackpunkt_id", "feedback_point_id"),
        ("befund_id", "finding_id"),
        ("metrik_typ_id", "metric_type_id"),
        ("art", "kind"),
        ("reihenfolge", "position"),
    ],
    "analysis_job": [
        ("art", "kind"),
        ("versuche", "attempts"),
        ("fehlertext", "error_text"),
        ("aktualisiert_am", "updated_at"),
    ],
}

# Enum-like values the code compares against, so they are part of the schema's
# vocabulary rather than user-visible content (which stays German).
#
# "laufend" maps onto "aborted" and not back: since ADR 0034 the row is written
# only after the Session ended, so a stored "laufend" is a Session that never
# finished -- which is what "aborted" means.
SESSION_STATUS = [("beendet", "completed"), ("abgebrochen", "aborted")]
SPEAKER = [("nutzer", "user")]
POINT_KIND = [("staerke", "strength"), ("verbesserung", "improvement")]
JOB_KIND = [("analyse", "analysis")]

# Constraints dev's own migrations named by hand, off the convention. The rest
# already follow it; the foreign keys below are dropped and recreated anyway,
# which renames them for free.
PK_UQ_RENAMES = [
    ("persona_objection", "pk_persona_einwand", "pk_persona_objection"),
    ("persona", "uq_persona_schluessel", "uq_persona_key"),
    ("scenario", "pk_szenario", "pk_scenario"),
    ("scenario", "uq_szenario_schluessel", "uq_scenario_key"),
    ("language", "pk_sprache", "pk_language"),
    ("metric_type", "pk_metrik_typ", "pk_metric_type"),
    ("metric_type", "uq_metrik_typ_schluessel", "uq_metric_type_key"),
    ("measurement", "pk_messung", "pk_measurement"),
    ("finding", "pk_befund", "pk_finding"),
    ("feedback_point", "pk_feedbackpunkt", "pk_feedback_point"),
    ("session", "uq_session_oeffentliche_id", "uq_session_extern_id"),
]

# --- 5. Deletes -----------------------------------------------------------

# (table, column, referred_table, referred_column, ondelete). The constraint
# name is derived from the convention in backend/db/base.py:
#   fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s
FOREIGN_KEYS = [
    ("persona", "language_code", "language", "code", None),
    ("persona_objection", "persona_id", "persona", "persona_id", "CASCADE"),
    ("session", "persona_id", "persona", "persona_id", None),
    ("session", "scenario_id", "scenario", "scenario_id", None),
    ("session", "language_code", "language", "code", None),
    ("turn", "session_id", "session", "session_id", "CASCADE"),
    ("measurement", "session_id", "session", "session_id", "CASCADE"),
    ("measurement", "metric_type_id", "metric_type", "metric_type_id", None),
    ("finding", "session_id", "session", "session_id", "CASCADE"),
    ("finding", "metric_type_id", "metric_type", "metric_type_id", "SET NULL"),
    ("feedback", "session_id", "session", "session_id", "CASCADE"),
    ("feedback_point", "feedback_id", "feedback", "feedback_id", "CASCADE"),
    ("feedback_point", "turn_id", "turn", "turn_id", "SET NULL"),
    ("feedback_point", "finding_id", "finding", "finding_id", "SET NULL"),
    ("feedback_point", "metric_type_id", "metric_type", "metric_type_id", "SET NULL"),
    ("analysis_job", "session_id", "session", "session_id", "CASCADE"),
]

# The foreign keys as they exist *before* this revision: German table and
# column names, no ON DELETE, and three names dev's own migrations chose by
# hand rather than by the convention -- which is why the names are written out
# instead of derived. Used twice: upgrade drops them by name, downgrade puts
# them back exactly as they were.
# (table, column, referred_table, referred_column, name)
OLD_FOREIGN_KEYS = [
    ("persona_einwand", "persona_id", "persona", "persona_id",
     "fk_persona_einwand_persona_id_persona"),
    ("session", "persona_id", "persona", "persona_id",
     "fk_session_persona_id_persona"),
    ("session", "szenario_id", "szenario", "szenario_id",
     "fk_session_szenario_id_szenario"),
    ("session", "sprache_code", "sprache", "sprache_code",
     "fk_session_sprache_code_sprache"),
    ("turn", "session_id", "session", "session_id",
     "fk_turn_session_id_session"),
    ("messung", "session_id", "session", "session_id", "fk_messung_session_id"),
    ("messung", "metrik_typ_id", "metrik_typ", "metrik_typ_id",
     "fk_messung_metrik_typ_id_metrik_typ"),
    ("befund", "session_id", "session", "session_id", "fk_befund_session_id"),
    ("befund", "metrik_typ_id", "metrik_typ", "metrik_typ_id",
     "fk_befund_metrik_typ_id_metrik_typ"),
    ("feedback", "session_id", "session", "session_id",
     "fk_feedback_session_id_session"),
    ("feedbackpunkt", "feedback_id", "feedback", "feedback_id",
     "fk_feedbackpunkt_feedback_id_feedback"),
    ("feedbackpunkt", "turn_id", "turn", "turn_id",
     "fk_feedbackpunkt_turn_id_turn"),
    ("feedbackpunkt", "befund_id", "befund", "befund_id",
     "fk_feedbackpunkt_befund_id_befund"),
    ("feedbackpunkt", "metrik_typ_id", "metrik_typ", "metrik_typ_id",
     "fk_feedbackpunkt_metrik_typ_id"),
    ("analysis_job", "session_id", "session", "session_id",
     "fk_analysis_job_session_id_session"),
]

# --- 4. Indexes -----------------------------------------------------------
# Every foreign-key column. feedback.session_id is absent: its UNIQUE
# constraint already provides the index.
INDEXED_FK_COLUMNS = [(t, c) for t, c, *_ in FOREIGN_KEYS if (t, c) != ("feedback", "session_id")]

# --- CHECK constraints ----------------------------------------------------
# Alembic does not autodetect these, so they are written out by hand. Names
# follow ck_%(table_name)s_%(constraint_name)s.
CHECKS = [
    ("session", "status_valid", "status IN ('completed', 'aborted')"),
    ("turn", "speaker_valid", "speaker IN ('user', 'persona')"),
    ("turn", "seq_index_non_negative", "seq_index >= 0"),
    ("turn", "start_offset_non_negative", "start_offset_ms >= 0"),
    ("turn", "duration_non_negative", "duration_ms IS NULL OR duration_ms >= 0"),
    ("feedback_point", "kind_valid", "kind IN ('strength', 'improvement')"),
    ("analysis_job", "kind_valid", "kind IN ('analysis', 'feedback')"),
    ("analysis_job", "status_valid",
     "status IN ('queued', 'running', 'done', 'failed')"),
]

# --- Timestamps -----------------------------------------------------------
# timezone=True throughout: a naive column silently loses the offset on read.
#
# Note what Postgres does to existing rows: `ALTER COLUMN ... TYPE timestamptz`
# reads the stored naive values as being in the server's TimeZone setting. That
# is correct for rows this application wrote (it passes local `datetime.now()`)
# and is in any case the only interpretation available -- the offset those rows
# were written with was never stored. Sessions recorded before this revision
# therefore keep their wall-clock time, not necessarily their instant.
TIMESTAMPS = [
    ("session", "started_at", False),
    ("session", "ended_at", True),
    ("feedback", "created_at", False),
    ("analysis_job", "updated_at", False),
]


def _fk_name(table: str, column: str, referred: str) -> str:
    return f"fk_{table}_{column}_{referred}"


def _index_name(table: str, column: str) -> str:
    return f"ix_{table}_{column}"


def _rename_values(table: str, column: str, pairs, reverse: bool = False) -> None:
    for old, new in pairs:
        source, target = (new, old) if reverse else (old, new)
        op.execute(f"UPDATE {table} SET {column} = '{target}' WHERE {column} = '{source}'")


def upgrade() -> None:
    """German schema -> English, plus indexes, checks and enforced deletes."""
    # Foreign keys go first: dropping them before the renames means the
    # recreate below can address every table and column by its new name.
    for table, _, _, _, name in OLD_FOREIGN_KEYS:
        op.drop_constraint(name, table, type_="foreignkey")

    for old, new in TABLES:
        op.rename_table(old, new)
    for table, columns in COLUMNS.items():
        for old, new in columns:
            op.alter_column(table, old, new_column_name=new)
    for table, old, new in PK_UQ_RENAMES:
        op.execute(f'ALTER TABLE {table} RENAME CONSTRAINT "{old}" TO "{new}"')

    # A Session still marked "laufend" never finished; see the note above.
    op.execute("UPDATE session SET status = 'abgebrochen' WHERE status = 'laufend'")
    _rename_values("session", "status", SESSION_STATUS)
    _rename_values("turn", "speaker", SPEAKER)
    _rename_values("feedback_point", "kind", POINT_KIND)
    _rename_values("analysis_job", "kind", JOB_KIND)

    # New columns are NOT NULL but the tables can already hold rows, so each is
    # added nullable, backfilled, then tightened. The backfills are the values
    # the seed writes anyway (provision.py runs at every startup and corrects
    # them), not invented data: 'de' and 'de_male' are what the only Persona in
    # personas.py carries.
    op.add_column("persona", sa.Column("language_code", sa.String(8), nullable=True))
    op.add_column("persona", sa.Column("tts_voice", sa.String(60), nullable=True))
    op.add_column("persona", sa.Column("kugelaudio_voice_id", sa.Integer(), nullable=True))
    op.execute("UPDATE persona SET language_code = 'de' WHERE language_code IS NULL")
    op.execute("UPDATE persona SET tts_voice = 'de_male' WHERE tts_voice IS NULL")
    op.alter_column("persona", "language_code", existing_type=sa.String(8), nullable=False)
    op.alter_column("persona", "tts_voice", existing_type=sa.String(60), nullable=False)

    op.add_column("scenario", sa.Column("active", sa.Boolean(), nullable=True))
    op.execute("UPDATE scenario SET active = true WHERE active IS NULL")
    op.alter_column("scenario", "active", existing_type=sa.Boolean(), nullable=False)

    for table, column, nullable in TIMESTAMPS:
        op.alter_column(table, column, type_=sa.DateTime(timezone=True),
                        existing_type=sa.DateTime(), existing_nullable=nullable)

    for table, column, referred, referred_column, ondelete in FOREIGN_KEYS:
        op.create_foreign_key(_fk_name(table, column, referred), table, referred,
                              [column], [referred_column], ondelete=ondelete)
    for table, column in INDEXED_FK_COLUMNS:
        op.create_index(_index_name(table, column), table, [column])
    for table, name, condition in CHECKS:
        op.create_check_constraint(name, table, condition)


def downgrade() -> None:
    """Exact inverse, in reverse order."""
    # The bare name, not the ck_-prefixed one: op.drop_constraint applies the
    # naming convention from backend/db/base.py itself, exactly as
    # create_check_constraint did above. Prefixing here would apply it twice.
    for table, name, _ in CHECKS:
        op.drop_constraint(name, table, type_="check")
    for table, column in INDEXED_FK_COLUMNS:
        op.drop_index(_index_name(table, column), table_name=table)
    for table, column, referred, _, _ in FOREIGN_KEYS:
        op.drop_constraint(_fk_name(table, column, referred), table, type_="foreignkey")

    for table, column, nullable in TIMESTAMPS:
        op.alter_column(table, column, type_=sa.DateTime(),
                        existing_type=sa.DateTime(timezone=True), existing_nullable=nullable)

    op.drop_column("scenario", "active")
    op.drop_column("persona", "kugelaudio_voice_id")
    op.drop_column("persona", "tts_voice")
    op.drop_column("persona", "language_code")

    _rename_values("analysis_job", "kind", JOB_KIND, reverse=True)
    _rename_values("feedback_point", "kind", POINT_KIND, reverse=True)
    _rename_values("turn", "speaker", SPEAKER, reverse=True)
    _rename_values("session", "status", SESSION_STATUS, reverse=True)

    for table, old, new in reversed(PK_UQ_RENAMES):
        op.execute(f'ALTER TABLE {table} RENAME CONSTRAINT "{new}" TO "{old}"')
    for table, columns in COLUMNS.items():
        for old, new in columns:
            op.alter_column(table, new, new_column_name=old)
    for old, new in reversed(TABLES):
        op.rename_table(new, old)

    for table, column, referred, referred_column, name in OLD_FOREIGN_KEYS:
        op.create_foreign_key(name, table, referred, [column], [referred_column])
