"""Rename schema objects from German to English

Revision ID: 6269b27b75f9
Revises: 41afa0461674
Create Date: 2026-09-01

Hand-written, not autogenerated. Autogenerate cannot recognise a rename — it
would emit a drop of every German table and a create of every English one,
destroying whatever Sessions are already stored. Renaming in place keeps the
rows and lets Postgres carry the foreign keys along by itself.
"""
from typing import Sequence, Union

from alembic import op

revision: str = '6269b27b75f9'
down_revision: Union[str, None] = '41afa0461674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# (old, new) — applied in this order on upgrade, reversed on downgrade.
TABLES = [
    ("persona_einwand", "persona_objection"),
    ("szenario", "scenario"),
    ("sprache", "language"),
    ("metrik_typ", "metric_type"),
    ("messung", "measurement"),
    ("befund", "finding"),
    ("feedbackpunkt", "feedback_point"),
]

# Keyed by the *new* table name: {table: [(old_column, new_column), ...]}
COLUMNS = {
    "persona": [
        ("schluessel", "key"),
        ("rolle", "role"),
        ("haltung", "traits"),
        ("verhalten", "behavior"),
        ("trainingsziel", "training_goal"),
        ("schwierigkeitsgrad", "difficulty"),
        ("sprache_code", "language_code"),
        ("aktiv", "active"),
    ],
    "persona_objection": [
        ("einwand_id", "objection_id"),
        ("reihenfolge", "position"),
    ],
    "scenario": [
        ("szenario_id", "scenario_id"),
        ("schluessel", "key"),
        ("typ", "scenario_type"),
        ("titel", "title"),
        ("beschreibung", "description"),
        ("aktiv", "active"),
    ],
    "language": [
        ("sprache_code", "code"),
        ("bezeichnung", "name"),
    ],
    "metric_type": [
        ("metrik_typ_id", "metric_type_id"),
        ("schluessel", "key"),
        ("bezeichnung", "name"),
        ("einheit", "unit"),
        ("aktiv", "active"),
    ],
    "session": [
        ("szenario_id", "scenario_id"),
        ("sprache_code", "language_code"),
        ("gestartet_am", "started_at"),
        ("beendet_am", "ended_at"),
    ],
    "turn": [
        ("nutzer_transkript", "user_transcript"),
        ("persona_transkript", "persona_transcript"),
        ("nutzer_dauer_ms", "user_duration_ms"),
        ("persona_dauer_ms", "persona_duration_ms"),
    ],
    "measurement": [
        ("messung_id", "measurement_id"),
        ("metrik_typ_id", "metric_type_id"),
        ("wert", "value"),
    ],
    "finding": [
        ("befund_id", "finding_id"),
        ("metrik_typ_id", "metric_type_id"),
        ("kategorie", "category"),
        ("beschreibung", "description"),
    ],
    "feedback": [
        ("zusammenfassung", "summary"),
        ("erstellt_am", "created_at"),
    ],
    "feedback_point": [
        ("feedbackpunkt_id", "feedback_point_id"),
        ("befund_id", "finding_id"),
    ],
    "analysis_job": [
        ("art", "kind"),
        ("versuche", "attempts"),
        ("fehlertext", "error_text"),
        ("aktualisiert_am", "updated_at"),
    ],
}

# Enum-like values the code compares against, so they are part of the schema's
# vocabulary rather than user-visible content (which stays German).
SESSION_STATUS = [("beendet", "completed"), ("abgebrochen", "aborted")]
JOB_KIND = [("analyse", "analysis")]

# metric_type.key is an identifier the analysis code will look up by, unlike
# metric_type.name, which is German display text and stays as it is.
METRIC_KEYS = [
    ("tempo", "speaking_rate"),
    ("lautstaerke", "loudness"),
    ("artikulation", "articulation"),
    ("sprechfluessigkeit", "fluency"),
    ("redundanz", "redundancy"),
    ("konkretheit", "concreteness"),
    ("phasengerechte_sprache", "phase_appropriate_language"),
    ("redeanteile", "talk_time_share"),
    ("aktives_zuhoeren", "active_listening"),
    ("kongruenz", "congruence"),
]


def _rename_values(table: str, column: str, pairs, reverse: bool = False) -> None:
    for old, new in pairs:
        source, target = (new, old) if reverse else (old, new)
        op.execute(
            f"UPDATE {table} SET {column} = '{target}' WHERE {column} = '{source}'"
        )


def upgrade() -> None:
    """Renames every German table and column to its English counterpart.

    Tables first, so the column renames below can all address the new names.
    Foreign keys follow automatically; only the constraint *names* keep their
    old wording, which is cosmetic and not worth a second migration.
    """
    for old, new in TABLES:
        op.rename_table(old, new)

    for table, columns in COLUMNS.items():
        for old, new in columns:
            op.alter_column(table, old, new_column_name=new)

    _rename_values("session", "status", SESSION_STATUS)
    _rename_values("analysis_job", "kind", JOB_KIND)
    _rename_values("metric_type", "key", METRIC_KEYS)


def downgrade() -> None:
    """Exact inverse: values back to German, then columns, then tables."""
    _rename_values("metric_type", "key", METRIC_KEYS, reverse=True)
    _rename_values("analysis_job", "kind", JOB_KIND, reverse=True)
    _rename_values("session", "status", SESSION_STATUS, reverse=True)

    for table, columns in COLUMNS.items():
        for old, new in columns:
            op.alter_column(table, new, new_column_name=old)

    for old, new in reversed(TABLES):
        op.rename_table(new, old)
