"""Consent decisions

Revision ID: a4d3558cbc0b
Revises: 18f5098dfb1b

The table behind ADR 0060: what a subject agreed to, when, and to which
wording. Append-only, so granting, withdrawing and granting again are three
rows and the newest one is the current state -- a decision is something that
happened at a moment, and overwriting it would destroy the only evidence that
it was ever made.

No foreign key on `subject_id`, for the same reason `session.subject_id` has
none (ADR 0031): identity lives in Keycloak and there is no local User table to
point at. Indexed, because every Session that ends reads this table to find out
whether it may be stored at all.

Autogenerated. Unusually, the CHECK constraints came out correct without help:
autogenerate cannot detect a *changed* CHECK (ADR 0027, CLAUDE.md), but it does
emit the ones declared on a table it is creating.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4d3558cbc0b'
down_revision: Union[str, None] = '18f5098dfb1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
    'consent',
    sa.Column('consent_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("purpose IN ('session_storage')", name=op.f('ck_consent_purpose_valid')),
    sa.CheckConstraint("status IN ('granted', 'withdrawn')", name=op.f('ck_consent_status_valid')),
    sa.PrimaryKeyConstraint('consent_id', name=op.f('pk_consent'))
    )
    op.create_index(op.f('ix_consent_subject_id'), 'consent', ['subject_id'], unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_consent_subject_id'), table_name='consent')
    op.drop_table('consent')
