"""Add the case fields (fallfakten, anrufziel, erfolgsbedingung) to szenario

Revision ID: b3f2a91c04de
Revises: c5d1a83f47e2

Hand-written rather than autogenerated, for the same reason as the revision
before it: autogenerate emits three NOT NULL columns with no backfill, which
fails on a `szenario` table that already has rows. All three are added
nullable, backfilled with the empty string, and only then made NOT NULL.

Empty is a legitimate value, not just a migration artefact: a Scenario without
case facts falls back to the improvisation the prompt frame asked for before
ADR 0045, which is what the user-authored Scenarios of ADR 0024 will look like.
So existing rows stay valid after this runs — they just behave as they did.

Running `scripts/seed_reference_data.py` afterwards is what puts the actual
case content in place. See ADR 0045.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3f2a91c04de'
down_revision: Union[str, None] = 'c5d1a83f47e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


CASE_COLUMNS = ('fallfakten', 'anrufziel', 'erfolgsbedingung')


def upgrade() -> None:
    for column in CASE_COLUMNS:
        op.add_column('szenario', sa.Column(column, sa.Text(), nullable=True))
        op.execute(f"UPDATE szenario SET {column} = '' WHERE {column} IS NULL")
        op.alter_column('szenario', column, nullable=False)


def downgrade() -> None:
    for column in reversed(CASE_COLUMNS):
        op.drop_column('szenario', column)
