"""Whether the tone suited the occasion, as prose on the feedback row

Revision ID: b6e2d914f70a
Revises: a91c5f70d8e3

F-35's own caveat says how much melody is appropriate depends on the occasion,
and nothing in the application said which occasion a call was. This column
holds the answer, written by the same model call as `feedback.summary` and
`feedback.phase_language`.

Prose and not a figure, on ADR 0056's grounds: the right register for a
complaint is not the right register for a price negotiation, no norm is
measured for either, and a number here would be the invented threshold ADR 0051
refused.

Added nullable and left unfilled, exactly as `c1f4a83b7d29` was. There is
nothing to backfill an existing row with: those wrap-ups came from a prompt
that was never given the occasion, so any value written now would be invented.
NULL means "not analysed", which is what the frontend omits the block for.

Written by hand rather than autogenerated. One nullable column needs no
detection, and autogenerate would have had to run against a live database.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "b6e2d914f70a"
down_revision: Union[str, None] = "a91c5f70d8e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("feedback", sa.Column("tone_fit", sa.Text(), nullable=True))


def downgrade() -> None:
    op.drop_column("feedback", "tone_fit")
