"""Split display fields from prompt fields on persona and szenario

Revision ID: c5d1a83f47e2
Revises: 407a1f8f2352

Hand-written rather than autogenerated: both columns are added nullable and
backfilled from the existing German text before being made NOT NULL, so this
also runs against tables that already have rows. See ADR 0043.

The backfill only guarantees the columns are populated; it does not translate
anything. Running `scripts/seed_reference_data.py` afterwards is what puts the
curated English prompt text and the short German teasers in place.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5d1a83f47e2'
down_revision: Union[str, None] = '407a1f8f2352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('persona', sa.Column('rolle_anzeige', sa.String(length=120), nullable=True))
    op.add_column('szenario', sa.Column('kurzbeschreibung', sa.String(length=240), nullable=True))

    # The existing rolle is the text the card used to show, so it is exactly
    # the right seed for the new display column.
    op.execute("UPDATE persona SET rolle_anzeige = rolle WHERE rolle_anzeige IS NULL")
    # beschreibung is longer than the new column allows, so the backfill takes
    # the leading 240 characters. Real teasers come from the seed script.
    op.execute(
        "UPDATE szenario SET kurzbeschreibung = LEFT(beschreibung, 240) "
        "WHERE kurzbeschreibung IS NULL"
    )

    op.alter_column('persona', 'rolle_anzeige', nullable=False)
    op.alter_column('szenario', 'kurzbeschreibung', nullable=False)


def downgrade() -> None:
    op.drop_column('szenario', 'kurzbeschreibung')
    op.drop_column('persona', 'rolle_anzeige')
