"""Follow-up scenario provenance

Revision ID: dc5b4557e6b1
Revises: f5b2d47a91c3

Written against `40bd4a8839f2` on its own branch and re-pointed at the merge:
`f5b2d47a91c3` had taken that parent, which left the chain with two heads and
every database test failing to migrate. Re-pointing rather than an `alembic
merge` revision, for the reason that one gives: both columns are purely
additive, so nothing here depends on what the other branch did and the order is
free.

The Session a Scenario was drafted from (ADR 0069), NULL for every other row.

Unique, not merely indexed: exactly one follow-up per Session, enforced where a
second worker run cannot argue with it -- `scripts/requeue_feedback.py` puts a
finished Session back on the queue, and the constraint is what stops that from
producing a second Scenario. Postgres allows many NULLs under a UNIQUE index,
so every hand-authored row and every built-in is unaffected.

`ON DELETE SET NULL`, the one such edge into `session` (ADR 0026 otherwise
reserves SET NULL for back-references a Session owns): a later Session may have
been played on the follow-up, and `session.scenario_id` is NOT NULL, so the row
has to outlive the Session it came from. `backend/deletion.py` deactivates it at
the same moment, which is what removes it from the library.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc5b4557e6b1'
down_revision: Union[str, None] = 'f5b2d47a91c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario', sa.Column('derived_from_session_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_scenario_derived_from_session_id'), 'scenario', ['derived_from_session_id'], unique=True)
    op.create_foreign_key(op.f('fk_scenario_derived_from_session_id_session'), 'scenario', 'session', ['derived_from_session_id'], ['session_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_scenario_derived_from_session_id_session'), 'scenario', type_='foreignkey')
    op.drop_index(op.f('ix_scenario_derived_from_session_id'), table_name='scenario')
    op.drop_column('scenario', 'derived_from_session_id')
    # ### end Alembic commands ###
